### ISSUE TITLE
Hosted weblate app/webhook

### ISSUE THREAD

**Issue by comradekingu** [eventoL/eventoL#502]
Would be nice to have
https://github.com/apps/hosted-weblate 

for
https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github

**Comment by FedeG** [comment]
I added this app to eventol but I having to restart weblate local code and this remove pending changes (sorry :confused:)
I'll try send changes in spanish for check configuration.

**Comment by comradekingu** [comment]
FedeG I'll read more about it, only thing I'm noticing so far is I am no longer an admin on Weblate / eventoL

**Comment by FedeG** [comment]
Hi Allan,

I had a configuration errors in Weblate because EventoL was in GNUtn
organization and now It's in EventoL organization (I moved it at 2017).
Today, I fixed configuration (in current configuration weblate send changes
automatically to github) and I added (re-add) you to administrators in
weblate page.

Could you confirm your perms in weblate page?

P.S. Thanks for you contrib and if you want, I can add your github user to
contributors in readme.

**Comment by comradekingu** [comment]
@FedeG Works for me :)
